export interface BadgeCatalogEntry {
  key: string;
  label: string;
  description: string;
  icon: string; // lucide-react icon name
  colorClass: string;
  actionType: "auto" | "admin" | "purchase" | "link";
  actionLabel: string;
  actionHref?: string;
  sortOrder: number;
}

export const BADGE_CATALOG: BadgeCatalogEntry[] = [
  {
    key: "staff",
    label: "Staff",
    description: "Bagian dari tim staff platform.",
    icon: "ShieldCheck",
    colorClass: "text-blue bg-blue/10 border-blue/20",
    actionType: "admin",
    actionLabel: "Diberikan admin",
    sortOrder: 0,
  },
  {
    key: "helper",
    label: "Helper",
    description: "Aktif membantu user lain di Discord komunitas.",
    icon: "Lightbulb",
    colorClass: "text-amber-400 bg-amber-400/10 border-amber-400/20",
    actionType: "link",
    actionLabel: "Join Discord",
    sortOrder: 1,
  },
  {
    key: "premium",
    label: "Premium",
    description: "Berlangganan paket Premium.",
    icon: "Gem",
    colorClass: "text-purple bg-purple/10 border-purple/20",
    actionType: "auto",
    actionLabel: "Upgrade ke Premium",
    actionHref: "/dashboard/settings#premium",
    sortOrder: 2,
  },
  {
    key: "verified",
    label: "Verified",
    description: "Email terverifikasi dan username sudah diatur.",
    icon: "BadgeCheck",
    colorClass: "text-sky-400 bg-sky-400/10 border-sky-400/20",
    actionType: "auto",
    actionLabel: "Otomatis",
    sortOrder: 3,
  },
  {
    key: "donor",
    label: "Donor",
    description: "Mendukung platform lewat donasi.",
    icon: "HeartHandshake",
    colorClass: "text-emerald-400 bg-emerald-400/10 border-emerald-400/20",
    actionType: "purchase",
    actionLabel: "Donate",
    sortOrder: 4,
  },
  {
    key: "gifter",
    label: "Gifter",
    description: "Menghadiahkan produk platform ke user lain.",
    icon: "Gift",
    colorClass: "text-pink-400 bg-pink-400/10 border-pink-400/20",
    actionType: "purchase",
    actionLabel: "Gift",
    sortOrder: 5,
  },
  {
    key: "image_host",
    label: "Image Host",
    description: "Berlangganan Image Host.",
    icon: "Star",
    colorClass: "text-emerald-400 bg-emerald-400/10 border-emerald-400/20",
    actionType: "purchase",
    actionLabel: "Purchase",
    sortOrder: 6,
  },
  {
    key: "domain_legend",
    label: "Domain Legend",
    description: "Menambahkan custom domain publik.",
    icon: "Rocket",
    colorClass: "text-orange-400 bg-orange-400/10 border-orange-400/20",
    actionType: "purchase",
    actionLabel: "Add Domain",
    sortOrder: 7,
  },
  {
    key: "og",
    label: "OG",
    description: "Termasuk 1.000 pengguna pertama platform.",
    icon: "Award",
    colorClass: "text-amber-300 bg-amber-300/10 border-amber-300/20",
    actionType: "auto",
    actionLabel: "Otomatis",
    sortOrder: 8,
  },
  {
    key: "server_booster",
    label: "Server Booster",
    description: "Boost server Discord komunitas.",
    icon: "Flame",
    colorClass: "text-red-400 bg-red-400/10 border-red-400/20",
    actionType: "link",
    actionLabel: "Boost",
    sortOrder: 9,
  },
  {
    key: "bug_hunter",
    label: "Bug Hunter",
    description: "Melaporkan bug ke tim platform.",
    icon: "Bug",
    colorClass: "text-green-400 bg-green-400/10 border-green-400/20",
    actionType: "link",
    actionLabel: "Report",
    actionHref: "/#contact",
    sortOrder: 10,
  },
  {
    key: "the_million",
    label: "The Million",
    description: "Badge perayaan untuk 1 juta pengguna.",
    icon: "PartyPopper",
    colorClass: "text-fuchsia-400 bg-fuchsia-400/10 border-fuchsia-400/20",
    actionType: "auto",
    actionLabel: "Otomatis",
    sortOrder: 11,
  },
  {
    key: "winner",
    label: "Winner",
    description: "Juara 1 event platform.",
    icon: "Trophy",
    colorClass: "text-amber-400 bg-amber-400/10 border-amber-400/20",
    actionType: "admin",
    actionLabel: "Diberikan admin",
    sortOrder: 12,
  },
  {
    key: "second_place",
    label: "Second Place",
    description: "Juara 2 event platform.",
    icon: "Medal",
    colorClass: "text-slate-300 bg-slate-300/10 border-slate-300/20",
    actionType: "admin",
    actionLabel: "Diberikan admin",
    sortOrder: 13,
  },
  {
    key: "third_place",
    label: "Third Place",
    description: "Juara 3 event platform.",
    icon: "Medal",
    colorClass: "text-orange-700 bg-orange-700/10 border-orange-700/20",
    actionType: "admin",
    actionLabel: "Diberikan admin",
    sortOrder: 14,
  },
];
